services:
  minecraft:
    image: itzg/minecraft-server:latest
    pull_policy: if_not_present
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.11"
      MOTD: "Welcome to A Server, the most original name for a Minecraft server."
      MAX_PLAYERS: 7
      DIFFICULTY: "normal"
      ENABLE_WHITELIST: true
      WHITELIST: "${A_SERVER_WHITELIST}" 
      SEED: "5911919407403917058"

    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
